#!/bin/sh
# buku-fzf - a bash script to open buku bookmarks using fzf
# Copyright © 2022 haupling12

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.
[ -z "$BROWSER" ] && BROWSER=firefox

buku -p -f 4 | sed 's/\t/ /g' | fzf -e --no-mouse | awk '{print $2}' | xargs -r -I {} $BROWSER {}
