#!/bin/bash

function main(){
	echo "Welcome..."
	sleep 1
	while [ 1 ]
	do
		seconds="$((($(date -d "12/25" +%s) - $(date +%s))))"
		clear
		printf "%02d days %02d hours %02d minutes %02d seconds %02d unitil\n"\
		"$((seconds/86400))" "$((seconds/3600%24))" "$((seconds/60%60))" "$((seconds%60))"
		sleep 1
	done
	exit 0
}
main
