#!/bin/sh

case $(echo "lofi\nall\ncountry" | fzf) in
    "lofi") cd $HOME/my-work/entertment/music/lofi-full/ && mpv --loop-playlist * --no-video --input-ipc-server=/tmp/mpvmusocket ;;
    "all") cd $HOME/my-work/entertment/music/ && mpv --loop-playlist * --no-video --input-ipc-server=/tmp/mpvmusocket ;;
    "country") cd $HOME/my-work/entertment/music/country/ && mpv --loop-playlist * --no-video --input-ipc-server=/tmp/mpvmusocket ;;
esac
